#use_frameworks!
use_modular_headers!
platform :ios, '9.0'

target 'ZHCPickerHelper_Example' do
  pod 'ZHCPickerHelper', :path => '../'

  target 'ZHCPickerHelper_Tests' do
    inherit! :search_paths

    
  end
end
